[package]
name = "quartz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libquartz = { git = "https://github.com/Bultek/libquartz.git" }
clap = "3.1"
colored = "2.0"
tokio = {version = "1.19.2", features = ["full"]}
futures = "0.3"